version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # Map Nginx's port 80 to localhost:3000
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Map backend port to localhost
    restart: always

  root:
    build:
      context: .
    ports:
      - "4000:4000" # Map root service port
    restart: always
